import Head from 'next/head';
import Image from 'next/image';
import About from '../components/home/About';
import Banner from '../components/home/Banner';
import Futures from '../components/home/Futures';
import HomeTitle from '../components/home/HomeTitle';
import Review from '../components/home/Review';
import Room from '../components/home/Room';
import RoomTitle from '../components/home/RoomTitle';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hotel Reservation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <Banner />
      </section>
      <section className=' bg-gray-100 py-8 '>
        <HomeTitle />
        <Futures />
      </section>
      <section className='py-10'>
        <RoomTitle />
        <Room />
      </section>
      <section className='w-full bg-gray-100'>
        <About />
      </section>
      <section className='w-full bg-gray-100'>
        <Review />
      </section>
    </div>
  );
}
