// export const CREAT_ROOM_REQUEST = 'CREAT_ROOM_REQUEST';
// export const CREAT_ROOM_SUCCESS = 'CREAT_ROOM_SUCCESS';
// export const CREAT_ROOM_FAIL = 'CREAT_ROOM_FAIL';

export const ALL_BOOKING_REQUEST = 'ALL_BOOKING_REQUEST';
export const ALL_BOOKING_SUCCESS = 'ALL_BOOKING_SUCCESS';
export const ALL_BOOKING_FAIL = 'ALL_BOOKING_FAIL';

export const CHECKING_BOOKING_REQUEST = 'CHECKING_ROOM_REQUEST';
export const CHECKING_BOOKING_SUCCESS = 'CHECKING_ROOM_SUCCESS';
export const CHECKING_BOOKING_RESET = 'CHECKING_BOOKING_RESET';
export const CHECKING_BOOKING_FAIL = 'CHECKING_ROOM_FAIL';

export const BOOKING_DAYS_REQUEST = 'BOOKING_DAYS_REQUEST';
export const BOOKING_DAYS_SUCCESS = 'BOOKING_DAYS_SUCCESS';
export const BOOKING_DAYS_FAIL = 'BOOKING_DAYS_FAIL';

export const MY_BOOKING_REQUEST = 'MY_BOOKING_REQUEST';
export const MY_BOOKING_SUCCESS = 'MY_BOOKING_SUCCESS';
export const MY_BOOKING_FAIL = 'MY_BOOKING_FAIL';

export const MONTH_STATS_REQUEST = 'MONTH_STATS_REQUEST';
export const MONTH_STATS_SUCCESS = 'MONTH_STATS_SUCCESS';
export const MONTH_STATS_FAIL = 'MONTH_STATS_FAIL';

export const DAYS_STATS_REQUEST = 'DAYS_STATS_REQUEST';
export const DAYS_STATS_SUCCESS = 'DAYS_STATS_SUCCESS';
export const DAYS_STATS_FAIL = 'DAYS_STATS_FAIL';
