export const CREAT_ROOM_REQUEST = 'CREAT_ROOM_REQUEST';
export const CREAT_ROOM_SUCCESS = 'CREAT_ROOM_SUCCESS';
export const CREAT_ROOM_FAIL = 'CREAT_ROOM_FAIL';

export const ALL_ROOM_REQUEST = 'ALL_ROOM_REQUEST';
export const ALL_ROOM_SUCCESS = 'ALL_ROOM_SUCCESS';
export const ALL_ROOM_FAIL = 'ALL_ROOM_FAIL';

export const DETAILS_ROOM_REQUEST = 'DETAILS_ROOM_REQUEST';
export const DETAILS_ROOM_SUCCESS = 'DETAILS_ROOM_SUCCESS';
export const DETAILS_ROOM_FAIL = 'DETAILS_ROOM_FAIL';

export const ROOM_SEARCH_REQUEST = 'ROOM_SEARCH_REQUEST';
export const ROOM_SEARCH_SUCCESS = 'ROOM_SEARCH_SUCCESS';
export const ROOM_SEARCH_FAIL = 'ROOM_SEARCH_FAIL';
